services:

  merchant-transactions:
    image: merchant-transactions:latest
    ports:
      - "8080:8080" # Map port 8080 on the host to port 8080 in the container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NUMERATOR_API_URL=http://numerator-api:3000 # Replace with your numerator API URL
    depends_on:
      - numerator-api

#  json-server:
#    image: vimagick/json-server
#    command: -h 0.0.0.0 -p 80 /config/db.json
#    stop_grace_period: 1s
#    ports:
#      - "80:80"
#    volumes:
#      - ./config:/config

  numerator-api:
    image: node:20-alpine
    command: sh -c "yarn install && node api.js"
    stop_grace_period: 1s
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./numerator-api:/app

#  tcpdump:
#    image: alpine
#    command: sh -c "apk add --no-cache ngrep && ngrep -l -s 200000 -d any -W byline -q -t '^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS) ' port 8080"
#    stop_grace_period: 1s
#    network_mode: "service:json-server"